/*
 * credofasterpartnerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package CredofasterPartnerApiClient

import(
	"credofasterpartnerapi_lib/configuration_pkg"
	"credofasterpartnerapi_lib/main_pkg"
	"credofasterpartnerapi_lib/events_pkg"
)
/*
 * Client structure as interface implementation
 */
type CREDOFASTERPARTNERAPI_IMPL struct {
     main main_pkg.MAIN
     events events_pkg.EVENTS
     config  configuration_pkg.CONFIGURATION
}

/**
     * Access to Configuration
     * @return Returns the Configuration instance
*/
func (me *CREDOFASTERPARTNERAPI_IMPL) Configuration() configuration_pkg.CONFIGURATION {
    return me.config
}
/**
     * Access to Main controller
     * @return Returns the Main() instance
*/
func (me *CREDOFASTERPARTNERAPI_IMPL) Main() main_pkg.MAIN {
    if(me.main) == nil {
        me.main = main_pkg.NewMAIN(me.config)
    }
    return me.main
}
/**
     * Access to Events controller
     * @return Returns the Events() instance
*/
func (me *CREDOFASTERPARTNERAPI_IMPL) Events() events_pkg.EVENTS {
    if(me.events) == nil {
        me.events = events_pkg.NewEVENTS(me.config)
    }
    return me.events
}

