/*
 * credofasterpartnerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package CredofasterPartnerApiClient

import(
	"credofasterpartnerapi_lib/configuration_pkg"
	"credofasterpartnerapi_lib/main_pkg"
	"credofasterpartnerapi_lib/events_pkg"
)


/*
 * Interface for the CREDOFASTERPARTNERAPI_IMPL
 */
type CREDOFASTERPARTNERAPI interface {
    Main()                  main_pkg.MAIN
    Events()                events_pkg.EVENTS
    Configuration()         configuration_pkg.CONFIGURATION
}

/*
 * Factory for the CREDOFASTERPARTNERAPI interface returning CREDOFASTERPARTNERAPI_IMPL
 */
func NewCREDOFASTERPARTNERAPI() CREDOFASTERPARTNERAPI {
    credofasterPartnerApiClient := new(CREDOFASTERPARTNERAPI_IMPL)
    credofasterPartnerApiClient.config = configuration_pkg.NewCONFIGURATION()

    return credofasterPartnerApiClient
}
