/*
 * credofasterpartnerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package main_pkg

import "credofasterpartnerapi_lib/configuration_pkg"
import "credofasterpartnerapi_lib/models_pkg"

/*
 * Interface for the MAIN_IMPL
 */
type MAIN interface {
    AirtimeRequest (*models_pkg.PartnerAirtimeRequest) ([]*models_pkg.PartnerAirtimeResponse, error)

    AirtimeBalance () (*models_pkg.PartnerAirtimeBalanceResponse, error)
}

/*
 * Factory for the MAIN interaface returning MAIN_IMPL
 */
func NewMAIN(config configuration_pkg.CONFIGURATION) *MAIN_IMPL {
    client := new(MAIN_IMPL)
    client.config = config
    return client
}