/*
 * credofasterpartnerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package configuration_pkg

import(
	"credofasterpartnerapi_lib/apihelper_pkg"
)
/* Setting up enums for Environments and Servers 
*/
type Environments int

type Servers int

// Environment Enums
const (
     PRODUCTION Environments = 1 + iota
     //For Test Purpose
     SANDBOX
     //Development
     DEVELOPMENT
)

// Servers Enums
const (
 	 ENUM_DEFAULT Servers = 1 + iota
   	 MY_CALLBACK_ENDPOINT
)

type CONFIGURATION_IMPL struct {
    /** Assigned APIKey */
    /** Replace the value of ApiKey with an appropriate value */
    apikey string
    /** Assigned ClientId */
    /** Replace the value of ClientId with an appropriate value */
    clientid string
}

/*
 * Getter function returning apikey
 */
func (me *CONFIGURATION_IMPL) ApiKey() string{
    return me.apikey
}

/*
 * Setter function setting up apikey
 */
func (me *CONFIGURATION_IMPL) SetApiKey(apiKey string) {
    me.apikey = apiKey
}

/*
 * Getter function returning clientid
 */
func (me *CONFIGURATION_IMPL) ClientId() string{
    return me.clientid
}

/*
 * Setter function setting up clientid
 */
func (me *CONFIGURATION_IMPL) SetClientId(clientId string) {
    me.clientid = clientId
}

// Setting up Default Environment
var Environment = SANDBOX

// A map of environments and their corresponding servers/baseurls
var EnvironmentsMap = map[Environments](map[Servers]string){

    PRODUCTION : map[Servers]string{
        ENUM_DEFAULT:"https://api.partner.credofaster.co.ke",
        MY_CALLBACK_ENDPOINT:"https://posthere.io/dfd0-4d32-8ad9",
    },

    SANDBOX : map[Servers]string{
        ENUM_DEFAULT:"https://api-test.partner.credofaster.co.ke",
        MY_CALLBACK_ENDPOINT:"https://posthere.io/dfd0-4d32-8ad9",
    },

    DEVELOPMENT : map[Servers]string{
        ENUM_DEFAULT:"https://partner.credofaster.co.ke/crm_api/api/",
        MY_CALLBACK_ENDPOINT:"https://partner.credofaster.co.ke/crm_api/api/",
    },
}
 
// Make and return the map of parameters
func GetBaseURIParameters(config CONFIGURATION) map[string]interface{} {
     kvpMap := map[string]interface{}{
    }
    return kvpMap;
}

// Gets the URL for a particular alias in the current environment and appends it with template parameters
// return the baseurl
func GetBaseURI(server Servers, config CONFIGURATION) string {
    url := EnvironmentsMap[Environment][server]
    appendedURL, _ := apihelper_pkg.AppendUrlWithTemplateParameters(url, GetBaseURIParameters(config))
    return appendedURL

}
