/*
 * credofasterpartnerapi_lib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

package events_pkg

import "credofasterpartnerapi_lib/configuration_pkg"
import "credofasterpartnerapi_lib/models_pkg"

/*
 * Interface for the EVENTS_IMPL
 */
type EVENTS interface {
    RegisterCallback (*models_pkg.RegisterCallbackRequest) (*models_pkg.RegisterCallbackResponse, error)

    ClientEventFeedback (*models_pkg.EventCallbackPayload) (*models_pkg.EventCallbackFeedback, error)
}

/*
 * Factory for the EVENTS interaface returning EVENTS_IMPL
 */
func NewEVENTS(config configuration_pkg.CONFIGURATION) *EVENTS_IMPL {
    client := new(EVENTS_IMPL)
    client.config = config
    return client
}